v2.8.2 (#256)
* Fixes "Missing Access" bug for ban command

* Fixes visit not ending after idletime #242 (#254)

* TypeError: endvisit reply is not a function (#255)

* Fix endvisit hostChannel.reply is not a function

* Add messageCollector ignore commands

* Change internal version to 2.8.2